### ISSUE TITLE
Can't install sn0int on Kali Linux Rolling

### ISSUE THREAD

**Issue by okoester** [kpcyrd/sn0int#123]
snOint fails to install on Kali Linux Rolling.
This is the output:

```
101 root@xxxxx ~/sn0int (git)-[master] # cargo install -f --path .                                                                                                                                                                           :(
  Installing sn0int v0.12.0 (/root/sn0int)
    Updating crates.io index
   Compiling ring v0.16.7
   Compiling url v2.1.0
error[E0658]: use of unstable library feature 'alloc': this library is unlikely to be stabilized in its current form or name (see issue #27783)
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.7/src/lib.rs:69:1
   |
69 | extern crate alloc;
   | ^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `ring`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `sn0int v0.12.0 (/root/sn0int)`, intermediate artifacts can be found at `/root/sn0int/target`

Caused by:
  build failed
cargo install -f --path .  13,62s user 0,31s system 120% cpu 11,591 total
```
How to fix that to test sn0int?

Regards
Olaf

---

## Versions

- **rustc --version:**
rustc 1.34.2
- **cargo --version:**
cargo 1.36.0
- **sn0int --version:**
not yet built due to the error described above

- **uname -a:**
Linux xxxxxx 4.19.0-kali5-amd64 #1 SMP Debian 4.19.37-6kali1 (2019-07-22) x86_64 GNU/Linux

## Environment

- **Operating System/Distro:**
$ cat /etc/issue:
Kali GNU/Linux Rolling \n \l

- **Installed from (source/apt/pacman/brew/docker):**
source (github.com) v0.12.0 
cloned two hours ago...

**Comment by kpcyrd** [comment]
Hey! Please see the install instructions for kali linux: https://sn0int.readthedocs.io/en/stable/install.html#debian-ubuntu-kali

You need to uninstall rust and cargo with apt and reinstall it with rustup from here: https://rustup.rs/

Alternatively you can also use the docker image instead (either the pre-built one from docker hub or by running `docker build -t sn0int .`)

rustc in kali is currently lagging behind due to:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=933045

I hope that helps!

**Comment by kpcyrd** [comment]
Closing since there's now an apt repo with pre-built packages: https://sn0int.readthedocs.io/en/stable/install.html#debian-ubuntu-kali
