### ISSUE TITLE
error trying to connect: Connection reset by peer (os error 104)

### ISSUE THREAD

**Issue by SHTLUOLEI** [kpcyrd/sn0int#243]
error trying to connect: Connection reset by peer (os error 104) Trying to connect: Connection reset by peer (OS Error 104)
![image](https://user-images.githubusercontent.com/112939682/233362732-e1e023e0-4692-4fa4-9600-dd860c7dd910.png)

I don't know what the reason is, is it self or server
The environment is kali linux2023.1
I am new, just follow the code on github to install, do not know what version of sn0int
![image](https://user-images.githubusercontent.com/112939682/233362801-86761f67-107d-41c1-a99f-aade9f5cf6ad.png)

**Comment by kpcyrd** [comment]
It seems you're not connected to the internet, it failed to connect to the registry it's downloading it's modules from.

**Comment by SHTLUOLEI** [comment]
My network must be working, or I wouldn't be able to ask for help on github

**Comment by leodahal4** [comment]
ConnectionResetError Errno 104 Connection reset by peer can occur due to sending requests after the server limit has been reached or making frequent requests without taking any breaks. Also, there could be a server problem, an authentication issue, or a location restriction behind the error.

**Comment by kpcyrd** [comment]
The registry is working correctly for me:

![image](https://user-images.githubusercontent.com/7763184/233844029-2431e819-f5e1-46d6-b86c-84cdf80bdd75.png)

It seems something is blocking your connection attempt to **sn0int.com:443**, but it's very difficult to tell what exactly is refusing the connection. You can troubleshoot this in a more isolated way like this:

```
curl -v https://sn0int.com:443/
```

It could be your computer configuration, it could be your local network, it could be blocking at your work network or an internet service provider (although I'm currently not aware of anybody blocking sn0int.com). If possible, try on a different internet connection.

If there's any systemic filtering/blocking in place I'd be very curious to learn about it, but since there doesn't seem to be an issue in sn0int the program I'm closing this issue for now.

If you need to use sn0int on an airgapped network I recommend downloading the modules into files (sn0int installs them to `~/.local/share/sn0int/modules`, every module is a single file), then run them with `sn0int run -f ./path/to/module.lua`

**Comment by SHTLUOLEI** [comment]
> 注册表为我正常工作：
> 
> ![image](https://user-images.githubusercontent.com/7763184/233844029-2431e819-f5e1-46d6-b86c-84cdf80bdd75.png)
> 
> 似乎有什么东西阻止了您**尝试 sn0int.com:443** 的连接，但很难说出究竟是什么在拒绝连接。您可以通过更隔离的方式对此进行故障排除，如下所示：
> 
> ```
> curl -v https://sn0int.com:443/
> ```
> 
> 它可能是您的计算机配置，可能是您的本地网络，它可能在您的工作网络或互联网服务提供商上阻塞（尽管我目前不知道有人阻止 sn0int.com）。如果可能，请尝试使用其他互联网连接。
> 
> 如果有任何系统过滤/阻塞，我会非常好奇地了解它，但由于 sn0int 程序中似乎没有问题，我现在正在关闭这个问题。
> 
> 如果您需要在气隙网络上使用 sn0int，我建议将模块下载到文件中（sn0int 将它们安装到 ，每个模块都是一个文件），然后运行它们`~/.local/share/sn0int/modules``sn0int run -f ./path/to/module.lua`

When I type curl -v https://sn0int.com:443/, this is what he says
![image](https://user-images.githubusercontent.com/112939682/233847113-e8116928-363c-4301-b7b7-26a7da4c977d.png)
